theme: just-the-docs
url: https://gitlab.fhnw.ch
aux_links:
  Repository: https://gitlab.fhnw.ch/
title: GDI Projekt
description: Speichere diese Seite als Bookmark und verfolge unseren Projektstand!
